server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
  port: 18089

spring:
  application:
    name: cjannuity-channel-outbound
  threads:
    virtual:
      enabled: true # JDK 21 虚拟线程开启
  profiles:
    include: local

retrofit:
  # 全局默认
  global-connect-timeout-ms: 2000
  global-read-timeout-ms: 5000
  # 针对支付宝的特殊配置 (无需改代码)
  timeout:
    com.example.outbound.server.infrastructure..alipay.AliPayRetrofitApi:
      read-timeout-ms: 8000
    com.example.outbound.server.infrastructure.sf.SfRetrofitClient:
      read-timeout-ms: 3000
    # 圆通接口可能比较慢，单独给它设置长一点的超时
    com.example.outbound.server.infrastructure.yto.YtoRetrofitClient:
      read-timeout-ms: 5000
