# sofa registry settings
spring:
  cloud:
    gateway.server.webflux:
    routes:
      - id: web
        uri: lb://mweb
        predicates:
          - Method=POST
          - Path=/web/**


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.alipay.cloud: DEBUG
    com.cjannuity.channel: DEBUG
